#160451499 Password Reset Functionality
andela/phlox-ah pull request #14
Opened 2018-10-08 08:05 UTC by slimsolz

#### What does this PR do?
It sends user reset password URL mail and allows a user to update his password

#### Description of Task to be completed?
- Create a sendMail function to send mail to the user using SendGrid
- Send mail to the user
- Validate the URL
- Allow user update password

#### How should this be manually tested?
- Clone the repo with "git clone https://github.com/andela/phlox-ah.git"
- cd into phlox-ah. cd phlox-ah
- Switch to the feature branch git branch -r then run git checkout feature/160451499/user-reset-password
- Run npm install
- Rename .env_sample file to .env then fill it with your locally created Postgres database details
- If you have PostgreSQL install you can create a database on your command line with createdb your_db_name
- Run npm run migrate-reset to migrate your table into your database
- Run npm run dev to start your server
- Open postman, then visit localhost:3000/api/v1//forget a Post request with the following form entry: email.
- A mail will be sent to your email account click to reset password
- Open postman, then visit localhost:3000/api/v1/reset_password a Put request with the following form entry: password.
- A successful registration completed will be displayed

#### What are the relevant pivotal tracker stories?
#160451499

2018-10-08 09:40 UTC, udochukwu reviewed
LGTM

2018-10-08 09:46 UTC, samdiano commented
LGTM

2018-10-08 10:49 UTC, s-akinrele commented on server/controllers/userController.js
> +        const options = {
confirm the copy text with your PO ..

2018-10-08 10:51 UTC, s-akinrele commented on server/controllers/userController.js
> +      .then((userFound) => {
just use `user`

2018-10-08 10:53 UTC, s-akinrele commented on server/helpers/mail.js
> +  const mailMessage = {
sync with @onwuvic to use the same helper.

2018-10-08 10:54 UTC, s-akinrele commented on server/routes/api/user.js
> +router.post('/forget', UserController.forgetPassword);
forgotPassword would be more appropriate here ..

2018-10-08 10:54 UTC, s-akinrele requested changes
Please update the PR with your test. Looking good overall.

2018-10-09 09:09 UTC, onwuvic commented on server/controllers/userController.js
> +        const options = {
PO has agreed with the text.

2018-10-09 09:15 UTC, onwuvic reviewed
LGTM

2018-10-09 09:41 UTC, s-akinrele approved these changes
GTM

2018-10-09 09:43 UTC, merged