Feature/160451500/facebook-google-login
andela/phlox-ah pull request #17
Opened 2018-10-10 07:13 UTC by udochukwu

**What does this PR do?**
This PR logs In a user into Authors Haven using Facebook or Google and returns a token

Description of Task to be completed?

- Install Facebook and google passport packages

- Configure the strategy configuration for Facebook and Google create a socialLoginController for handling login/signup requests via Facebook or Google 

- Create a social login route.

- Update .env_sample file

**What are the relevant pivotal tracker stories?**
https://www.pivotaltracker.com/story/show/160451500

**Screenshots (if appropriate)**

-N/A

**Questions:```**

-N/A

2018-10-10 09:47 UTC, onwuvic commented on .env_sample
> +GOOGLE_APP_ID=secret
Add a new line here

2018-10-10 09:50 UTC, onwuvic commented on server/config/facebookStrategy.js
> +    callbackURL: 'http://localhost:3000/api/v1/login/facebook/return',
I think you use `req.headers.host` instead of manually adding `http://localhost:3000`

2018-10-10 09:51 UTC, slimsolz commented on server/config/googleStrategy.js
> +    callbackURL: 'http://localhost:3000/api/v1/login/google/return',
In place of `localhost:3000` I think you should use `req.headers.host`

2018-10-11 09:37 UTC, onwuvic reviewed
LGTM

2018-10-11 09:49 UTC, s-akinrele commented on server/controllers/socialLoginController.js
> +  static modelQuery(user, done) {
@udochukwu kindly use a more meaningful name for this method, a name that describes what it is doing.

2018-10-11 09:49 UTC, s-akinrele commented on server/controllers/socialLoginController.js
> +  static response(req, res) {
@udochukwu the same applies  here

2018-10-11 09:50 UTC, s-akinrele commented on server/controllers/socialLoginController.js
> +    }).spread((foundOrCreated, created) => {
what exactly was found here @udochukwu, please use a descriptive name for the variable here too

2018-10-11 09:51 UTC, s-akinrele commented on server/index.js
>  // app.use(require("method-override")());
remove commented code

2018-10-11 09:53 UTC, s-akinrele requested changes
I had some comments @udochukwu

2018-10-11 10:54 UTC, s-akinrele approved these changes

2018-10-11 10:58 UTC, merged