This commit add the functionality to like an article
andela/phlox-ah pull request #18
Opened 2018-10-10 09:56 UTC by samdiano

#### What does this PR do?
Creates endpoint to like an article
#### Description of Task to be completed?
- create like model
- create like controller
- creat routes to like and dislike an article

Have these endpoints working.
`POST /api/v1/articles/:slug/like` 
`POST /api/v1/articles/:slug/disllike` 

#### How should this be manually tested?
After cloning the repo, cd into it and RUN `npm install`, set env variables, and run migration
- Using Postman, test the endpoints above.
- To test authentication, add `x-access-token: JWT TOKEN`. Get the TOKEN from signup endpoint
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#160451505

2018-10-10 09:59 UTC, samdiano commented on server/controllers/articleController.js
> +        res.status(404).json({ message: 'article does not exist', success: 'false' });
I changed the response object to match the team's response convention

2018-10-10 10:02 UTC, samdiano commented on server/controllers/articleController.js
> +      include: [{
I included the likes of an article when fetching the articles

2018-10-10 16:30 UTC, samdiano commented on server/routes/api/article.js
> +router.get('/articles/:slug', ArticleController.getSingleArticle);
I removed the checkToken middleware to enable unauthenticated users to view an article.

2018-10-11 09:46 UTC, onwuvic reviewed
LGTM. Why is Travis failing?

2018-10-11 09:48 UTC, slimsolz reviewed
LGTM but I think you should get your tests to pass

2018-10-11 09:49 UTC, samdiano commented
Travis is failing because I just created seeders folder, and it's not in the staging branch.

2018-10-11 09:53 UTC, udochukwu reviewed
LGTM

2018-10-11 10:01 UTC, s-akinrele commented on server/routes/api/article.js
> +router.post('/articles/:slug/:likeType', checkToken, LikeController.likeArticle);
I think `:likeType'` can be a query parameter instead. e.g `?query=value&query=value` @samdiano

2018-10-11 10:02 UTC, s-akinrele requested changes
I had some comments

2018-10-11 10:28 UTC, s-akinrele approved these changes

2018-10-11 10:58 UTC, merged