#160451512 articles should have number of time it takes to read it
andela/phlox-ah pull request #20
Opened 2018-10-11 09:03 UTC by onwuvic

#### What does this PR do?
This PR add read time of all articles

#### Description of Task to be completed?
- Create a function that calculate the time it takes to read an article
- Test the function
- Calculate read time and save it to the database

#### How should this be manually tested?
- Create an article and it will calculate then save the article read time

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
Story type: feature
Story title: Users should be able to see time it takes to read an article
Story ID: #160451512

#### Screenshots (if appropriate)
N/A

#### Questions:```
N/A

2018-10-11 09:05 UTC, onwuvic commented on server/controllers/articleController.js
> +      title, body, userId: req.user.id, description, slug: `${slug(title)}-${uuid()}`, imgUrl, readTime
Add the read time to the database

2018-10-11 09:07 UTC, onwuvic commented on server/migrations/20181003095441-create-article.js
> +      type: Sequelize.INTEGER,
add readTime field to article model

2018-10-11 09:08 UTC, onwuvic commented on server/models/article.js
> +      type: DataTypes.INTEGER,
add readTime field to article model

2018-10-11 09:09 UTC, onwuvic commented on server/tests/article.test.js
> -  description: faker.lorem.sentences()
Faker library is causing irregularity on the test case, so i decided to replace it with plain text.

2018-10-11 09:10 UTC, onwuvic commented on server/tests/article.test.js
> -  description: faker.random.words()
Faker library is causing irregularity on the test case, so I decided to replace it with plain text.

2018-10-11 09:10 UTC, onwuvic commented on server/tests/article.test.js
> -  description: faker.random.words()
Faker library is causing irregularity on the test case, so I decided to replace it with plain text.

2018-10-11 09:10 UTC, onwuvic commented on server/tests/article.test.js
> -  body: faker.random.words()
Faker library is causing irregularity on the test case, so I decided to replace it with plain text.

2018-10-11 09:10 UTC, onwuvic commented on server/tests/articleModels.test.js
> -  body: faker.random.words(),
Faker library is causing irregularity on the test case, so I decided to replace it with plain text.

2018-10-11 09:11 UTC, onwuvic commented on server/tests/articleModels.test.js
> -  description: faker.random.words()
Faker library is causing irregularity on the test case, so I decided to replace it with plain text.

2018-10-11 09:11 UTC, onwuvic commented on server/tests/articleModels.test.js
> -  description: faker.random.words(),
Faker library is causing irregularity on the test case, so I decided to replace it with plain text.

2018-10-11 09:11 UTC, onwuvic commented on server/tests/articleModels.test.js
> -  body: faker.random.words(),
Faker library is causing irregularity on the test case, so I decided to replace it with plain text.

2018-10-11 09:45 UTC, oladimillion reviewed
LGTM

2018-10-11 09:50 UTC, samdiano reviewed
LGTM

2018-10-11 09:58 UTC, slimsolz reviewed
LGTM

2018-10-11 10:36 UTC, s-akinrele requested changes
Fix as discussed

2018-10-11 12:05 UTC, s-akinrele commented
fix your merge conflicts

2018-10-11 15:26 UTC, onwuvic commented on server/controllers/articleController.js
> -        res.status(200).json({ message: 'article retrieved successfully', success: 'true', article });
I change the success message because it was supposed to be boolean true data-type not string true

2018-10-11 15:27 UTC, onwuvic commented on server/tests/articleModels.test.js
> +  description: faker.lorem.sentence(),
added faker back to generate the mock data

2018-10-12 09:57 UTC, s-akinrele approved these changes

2018-10-12 09:57 UTC, merged