#160451508 User should be able to tag articles
andela/phlox-ah pull request #26
Opened 2018-10-12 07:03 UTC by kampkelly

#### What does this PR do?
This pull request adds tagging of articles.

#### Description of Task to be completed?
- Write tests for tagging articles
- Write the code to tag an article

#### How should this be manually tested?
After cloning the project, run `npm install`, then `npm run watch` to start the server. Using postman and as a signed in user, make requests to the following api endpoints.

To create a tag: /api/v1/tags -> POST request (params: name)
To retrieve tags: /api/v1/tags -> GET request
To tag articles: /api/v1/articles -> POST request (params: title, body, description, tags)

#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
#160451508
#### Questions:```
None

2018-10-12 08:09 UTC, kampkelly commented on server/controllers/articleController.js
> +      Article.create({
This change here gets the ids of the tags sent along with the request. Then the article is created and the tagged. Then, the article is returned with the tags.

2018-10-12 08:11 UTC, kampkelly commented on server/controllers/articleController.js
> +            .then((updatedArticle) => {
This change here gets the ids of the tags sent along with the request. Then the article is found, updated and tagged. Then, the article is returned with the tags.

2018-10-12 08:26 UTC, kampkelly commented on server/controllers/tagController.js
> +  static createTag(req, res) {
The createTag gets the array of tags from the body and creates it if it doesn't exist

2018-10-12 08:27 UTC, kampkelly commented on server/helpers/tags/getTagIds.js
> +export default getTagIds;
This helper returns the ids of the tags sent in the request to the create and update articles endpoints.

2018-10-12 08:54 UTC, kampkelly commented on server/helpers/validations/joiValidations.js
> +export default joiValidations;
This block of code is used by all the validations in the middlewares. So it has been moved to it s own file.

2018-10-12 09:33 UTC, onwuvic reviewed
LGTM

2018-10-12 09:36 UTC, onwuvic commented
Resolve your merge conflict

2018-10-12 10:06 UTC, s-akinrele commented on .eslintignore
> +/server/seeders/*.js
add a new line here

2018-10-12 10:18 UTC, s-akinrele commented on server/controllers/articleController.js
>        if (article === null) {
change as discussed.

2018-10-12 10:20 UTC, s-akinrele commented on server/controllers/articleController.js
> +      if (article === null) {
fix as discussed.

2018-10-12 10:24 UTC, s-akinrele commented on server/helpers/validations/joiValidations.js
> +export default joiValidations;
rename this method

2018-10-12 10:27 UTC, s-akinrele requested changes
Fix changes as discussed

2018-10-15 10:14 UTC, s-akinrele commented on server/controllers/articleController.js
> +      // include: [
remove commented code.

2018-10-15 10:25 UTC, s-akinrele approved these changes

2018-10-15 10:26 UTC, merged