#160451511 Search Functionality
andela/phlox-ah pull request #33
Opened 2018-10-16 09:26 UTC by slimsolz

#### What does this PR do?
Allows the user search for articles based on different parameters
#### Description of Task to be completed?
- Add route to search based on the article name or the author or tags

#### How should this be manually tested?
- Clone the repo with "git clone https://github.com/andela/phlox-ah.git"
- cd into phlox-ah. cd phlox-ah
- Switch to the feature branch git branch -r then run git checkout feature/160451511/search-functionality
- Run npm install
- Rename .env_sample file to .env then fill it with your locally created Postgres database details
- If you have PostgreSQL install you can create a database on your command line with createdb your_db_name
- Run npm run migrate-reset to migrate your table into your database
- Run npm run dev to start your server
- Open postman, then visit 
- To search: `POST localhost:3000/api/v1/search`

#### What are the relevant pivotal tracker stories?
#160451511

2018-10-16 09:29 UTC, oladimillion reviewed
LGTM

2018-10-16 09:42 UTC, slimsolz commented on server/seeders/20181010134458-demo-article.js
> +    title: 'title1',
I changed this so I could search for similar articles of different authors in my test

2018-10-16 10:55 UTC, s-akinrele requested changes
As discussed

2018-10-17 09:47 UTC, slimsolz commented on server/helpers/article.js
> +/* eslint-disable no-restricted-globals */
Add this because eslint flagged isNaN

2018-10-17 10:03 UTC, s-akinrele approved these changes

2018-10-17 10:04 UTC, merged