#160451521 user should be able to track comments history
andela/phlox-ah pull request #35
Opened 2018-10-17 06:52 UTC by kampkelly

#### What does this PR do?
This pull request adds keeping records of comments history

#### Description of Task to be completed?
- Write tests for tracking comment history
- Write the code to track comment history

#### How should this be manually tested?
After cloning the project, run `npm install`, then `npm run watch` to start the server. Using postman and as a signed in user, make requests to the following api endpoints.

To update a comment: /api/v1/articles/:articleSlug/comments/commentId/edit -> PUT request (params: comment)
To retrieve comment history for a user: /api/v1/articles/:articleSlug/comments/:commentId/myhistory -> GET request
To retrieve comment history for all users: /api/v1/articles/:articleSlug/comments/:commentId/allhistory -> GET request

#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
#160451521
#### Questions:```
None

2018-10-17 07:49 UTC, kampkelly commented on server/controllers/commentHistoryController.js
> +        getCommentHistory(searchParams, res, 'comment history retrieved', 'you have no histories for this comment');
This is calling a helper function. The same block of code was used in multiple functions in this controller. So I moved it to a helper function. The strings sent along are the specific response messages for this function.

2018-10-17 07:50 UTC, kampkelly commented on server/controllers/commentHistoryController.js
> +        getCommentHistory(searchParams, res, 'all comment histories retrieved', 'there are no histories for this comment');
This is calling a helper function. The same block of code was used in multiple functions in this controller. So I moved it to a helper function. The strings sent along are the specific response messages for this function.

2018-10-17 09:48 UTC, slimsolz reviewed
LGTM

2018-10-17 09:55 UTC, kampkelly commented on server/helpers/article.js
> +  // eslint-disable-next-line
Eslint is throwing an error on isNaN ---> 'no-restricted-globals'. So I disabled the check for this line.

2018-10-17 09:57 UTC, samdiano reviewed
LGTM

2018-10-17 10:16 UTC, s-akinrele commented on server/tests/commentsHistory.models.test.js
> +const validCommentHistory = {
move it to another file

2018-10-17 10:17 UTC, s-akinrele commented on server/tests/commentsHistory.test.js
> +  username: faker.internet.userName(),
and this

2018-10-17 10:18 UTC, s-akinrele requested changes
I had some comments

2018-10-18 10:01 UTC, s-akinrele approved these changes

2018-10-18 10:03 UTC, merged