#160451517 Users should be able to like a specific comment
andela/phlox-ah pull request #36
Opened 2018-10-17 07:15 UTC by samdiano

#### What does this PR do?
This pull request creates functionality to like and dislike a specific comment and replies

#### Description of Task to be completed?
- Write tests for liking a specific comment
- Write the code to like a specific comment

#### How should this be manually tested?
After cloning the project, run `npm install`, then `npm run watch` to start the server. Using postman and as a signed in user, make requests to the following API endpoints.

To like a comment: /api/v1/articles/:articleSlug/comments/:commentId/like -> POST request
To like a comment reply: /api/v1/articles/:articleSlug/comments/:commentId/reply/:replyId/like -> POST request
To dislike a comment: /api/v1/articles/:articleSlug/comments/:commentId/dislike -> POST request
To dislike a comment reply: /api/v1/articles/:articleSlug/comments/:commentId/reply/:replyId/dislike -> POST request

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#160451517

2018-10-17 09:19 UTC, samdiano commented on server/controllers/articleController.js
> +          {
I included the details of the user that liked an article

2018-10-17 09:21 UTC, samdiano commented on server/controllers/likeController.js
> +    const message = 'you liked this article';
refactored the implementation of liking an article as the former implementation causes conflicts

2018-10-17 09:24 UTC, samdiano commented on server/helpers/article.js
> +/* eslint-disable no-restricted-globals */
added this because eslint flagged isNaN as a restricted global method

2018-10-17 09:26 UTC, samdiano commented on server/models/articlecomment.js
> +    ArticleComment.hasMany(models.LikeComment, {
Added relationship between ArticleComment and likeComment models

2018-10-17 09:27 UTC, samdiano commented on server/routes/api/article.js
> +router.post('/articles/:slug/like', checkToken, LikeController.likeArticle);
Changed routes to define like and dislike explicitly

2018-10-17 09:29 UTC, samdiano commented on server/tests/article.test.js
>    });
removed like tests from article.test.js and moved it to like.test.js

2018-10-17 09:29 UTC, samdiano commented on server/tests/comment.test.js
> +  it('Should get all comments of an article', (done) => {
Added test to get all comments. It was not tested before

2018-10-17 09:59 UTC, slimsolz reviewed
LGTM

2018-10-17 10:01 UTC, kampkelly commented
LGTM

2018-10-17 10:26 UTC, s-akinrele requested changes
As discussed

2018-10-18 09:29 UTC, onwuvic reviewed
LGTM

2018-10-18 10:04 UTC, s-akinrele commented on server/controllers/likeCommentController.js
> +            dislike: false
please remove this line of code

2018-10-18 10:07 UTC, s-akinrele commented on server/controllers/likeReplyController.js
> +            dislike: true
remove this also

2018-10-18 10:47 UTC, s-akinrele approved these changes

2018-10-18 10:47 UTC, merged