Feature that allows users to report an article
andela/phlox-ah pull request #38
Opened 2018-10-17 14:16 UTC by oladimillion

#### What does this PR do?
This PR add functionality that allows user to report an article

#### Description of Task to be completed?
Write the code that handles article report functionality
Write tests for article report functionality

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
Story type: feature
Story title: Users should be able to report an article
Story ID: #160451516

#### Screenshots (if appropriate)
N/A

#### Questions:```
N/A

2018-10-17 14:18 UTC, oladimillion commented on server/models/articlecomment.js
> -    ArticleComment.hasMany(models.Reply, {
Forgot to remove this part when I was working on article comment reply

2018-10-18 09:29 UTC, slimsolz reviewed
LGTM

2018-10-18 09:36 UTC, onwuvic reviewed
LGTM

2018-10-18 09:49 UTC, samdiano reviewed
LGTM

2018-10-18 10:29 UTC, s-akinrele requested changes
As discussed

2018-10-19 18:11 UTC, s-akinrele approved these changes
thanks for the updates!

2018-10-19 18:11 UTC, merged