Feature/160451496/signup jwt
andela/phlox-ah pull request #8
Opened 2018-10-02 18:13 UTC by udochukwu

**What does this PR do?**

Users should receive a JWT on Successful Registration

**Description of Task to be completed?**

- modify the user migrations and models to accept username

- install Jsonwebtoken and create auth middlewares for signing and verifying tokens

- modify the create method under userController to return a token on successful signup

-  write tests for the user signup 

- add a .eslintignore file to skip Auto-generated files 

**What are the relevant pivotal tracker stories?**

#160451496

2018-10-03 09:47 UTC, onwuvic reviewed
LTGM

2018-10-03 09:54 UTC, kampkelly commented
LGTM

2018-10-03 10:09 UTC, s-akinrele commented on server/controllers/userController.js
>  const { User } = Model;
`import {User} from '../models';`

2018-10-03 10:19 UTC, s-akinrele commented on server/middlewares/authenticator.js
> +    const token = jwt.sign({ user }, process.env.JWTKEY, { expiresIn: '10000s' });
lets update this to 2 days

2018-10-03 10:22 UTC, s-akinrele commented on server/routes/api/user.js
> +router.get('/', (req, res) => res.json('welcome Author Haven'));
please put back the deleted code

2018-10-03 10:25 UTC, s-akinrele requested changes
Kindly add more tests and update the PR.

2018-10-03 13:37 UTC, udochukwu commented on server/controllers/userController.js
>  const { User } = Model;
I tried this solution it didn't work. I went to stack overflow and this is the solution https://github.com/andela/phlox-ah/pull/8

2018-10-03 13:53 UTC, s-akinrele commented on server/controllers/userController.js
> +        username,
can this be on a single line ``` .then(hashedPassword => User.create({ username, email, password: hashedPassword })

2018-10-03 13:53 UTC, s-akinrele commented on server/controllers/userController.js
> +          res.status(201).json({
same applies here

2018-10-03 13:54 UTC, s-akinrele commented on server/middlewares/authenticator.js
> +        .json({
can this be on a single line

2018-10-03 13:54 UTC, s-akinrele commented on server/middlewares/authenticator.js
> +            res.status(403)
no need for multiple lines

2018-10-03 13:55 UTC, s-akinrele reviewed
I had some comments, also I am yet to see the model test. @udochukwu

2018-10-03 15:12 UTC, s-akinrele commented on server/tests/user.test.js
> +  it('SShould throw an error 403', (done) => {
this should be `Should` @udochukwu

2018-10-03 15:21 UTC, udochukwu commented on server/tests/user.test.js
> +  it('SShould throw an error 403', (done) => {
I have corrected the error.

2018-10-04 10:06 UTC, s-akinrele commented on server/index.js
> +/* eslint-disable no-unused-vars */
Can you add this rule to eslint file

2018-10-04 10:06 UTC, s-akinrele approved these changes

2018-10-04 10:26 UTC, merged